-- https://github.com/folke/which-key.nvim

pack {
  src = 'https://github.com/folke/which-key.nvim',
  name = 'which-key',
  opts = {
    delay = 0,
    icons = {
      mappings = vim.g.have_nerd_font,
      keys = vim.g.have_nerd_font and {} or {
        Up = '<Up> ',
        Down = '<Down> ',
        Left = '<Left> ',
        Right = '<Right> ',
        C = '<C-…> ',
        M = '<M-…> ',
        D = '<D-…> ',
        S = '<S-…> ',
        CR = '<CR> ',
        Esc = '<Esc> ',
        ScrollWheelDown = '<ScrollWheelDown> ',
        ScrollWheelUp = '<ScrollWheelUp> ',
        NL = '<NL> ',
        BS = '<BS> ',
        Space = '<Space> ',
        Tab = '<Tab> ',
        F1 = '<F1>',
        F2 = '<F2>',
        F3 = '<F3>',
        F4 = '<F4>',
        F5 = '<F5>',
        F6 = '<F6>',
        F7 = '<F7>',
        F8 = '<F8>',
        F9 = '<F9>',
        F10 = '<F10>',
        F11 = '<F11>',
        F12 = '<F12>',
      },
    },

    spec = {
      { '<leader>d', group = '[D]iagnostic' },
      { '<leader>l', group = '[L]sp' },
      { '<leader>m', group = '[M]acro' },
      { '<leader>s', group = '[S]earch' },
      { '<leader>t', group = '[T]oggle' },
      { '<leader>c', group = '[C]olorscheme' },
      { '<leader>w', group = '[W]orkspace' },
      -- { '<leader>r', group = '[R]ename' },
      -- { '<leader>h', group = 'Git [H]unk',  mode = { 'n', 'v' } },
    },
  },
}
